version: '3.8'

services:
  checklistplus-app:
     image: 192.168.1.100:5000/checklistplus-app
     ports:
      - "3004:80"
     volumes:
      - ./nginx_data:/usr/share/nginx/html/checklistplus
     depends_on:
      - checklistplus-php
      - checklistplus-mysql
     networks:
      - my-checklist-plus-network  
     deploy:
      replicas: 1
      restart_policy:
        condition: on-failure 
  checklistplus-mysql:
      image: 192.168.1.100:5000/checklistplus-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=db
        - MYSQL_DATABASE=checklistplus
        - MYSQL_ROOT_HOST=%
      networks:
        - my-checklist-plus-network
      restart: always
      ports:
       - 3308:3306
      volumes:
        - ./mysql_custom/my.cnf:/etc/my.cnf
        - ./mysql_data/:/var/lib/mysql
      deploy:
        replicas: 2
        restart_policy:
          condition: on-failure   
  checklistplus-php:
       image: 192.168.1.100:5000/checklistplus-php
       networks:
        - my-checklist-plus-network
       ports:
        - 3005:9000
       restart: always 
       volumes:
        - ./checklist-backend:/var/www/html/checklistplus/api
       depends_on:
        - checklistplus-mysql
       deploy:
        replicas: 2
        restart_policy:
          condition: on-failure      
networks:
  my-checklist-plus-network:
    driver: overlay
    attachable: true