version: '3.8'
services:
  checklistplus-app:
     image: 172.31.160.1:5000/checklistplus-app:v1
     ports:
      - "3004:80"
     volumes:
      - ./nginx_data/html:/usr/share/nginx/html
     depends_on:
      - checklistplus-php
      - checklistplus-mysql
     networks:
      - my-checklist-plus-network
      - jenkins-overlay
     deploy:
      replicas: 1
      restart_policy:
        condition: on-failure 
  checklistplus-mysql:
      image: 172.31.160.1:5000/checklistplus-mysql:v1
      environment:
        - MYSQL_ROOT_PASSWORD=db
        - MYSQL_DATABASE=checklistplus
        - MYSQL_ROOT_HOST=%
      networks:
        - my-checklist-plus-network
        - jenkins-overlay
      restart: always
      ports:
       - 3308:3306
      volumes:
        - ./mysql_custom/my.cnf:/etc/my.cnf
        - ./mysql_data/:/var/lib/mysql
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure   
  checklistplus-php:
       image: 172.31.160.1:5000/checklistplus-php:v1
       networks:
        - my-checklist-plus-network
        - jenkins-overlay
       ports:
        - 3005:9000
       restart: always 
       volumes:
        - ./checklist-backend:/var/www/html/checklistplus/api
       depends_on:
        - checklistplus-mysql
       deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
           
networks:
  my-checklist-plus-network:
    driver: overlay
    attachable: true
  jenkins-overlay:
    external: true  

